In [1]:
import numpy as np
import pandas as pd

## Timestamp Objects
> Time stamps reference particular moments in time (e.g.,Oct 24th,2022 at 7:00pm)

### Creating timestamp objects

In [27]:
## variations
pd.Timestamp('2025/10/13')
pd.Timestamp('2025-10-13')
pd.Timestamp('2025.10.13')
# pd.Timestamp('2025,10,13')  ## not work
pd.Timestamp('2025, 10, 13')

Timestamp('2025-10-13 00:00:00')

In [23]:
## only year
pd.Timestamp('2025')

Timestamp('2025-01-01 00:00:00')

In [25]:
## using text
pd.Timestamp('13th Oct 2025')

Timestamp('2025-10-13 00:00:00')

In [35]:
## providing time also
pd.Timestamp('2025, 10, 13, 1:13pm')
pd.Timestamp('2025, 10, 13, 1:13')

Timestamp('2025-10-13 01:13:00')

In [37]:
## using datetime.datetime object
import datetime as dt
dt.datetime(2025,10,13,1,19,50)

datetime.datetime(2025, 10, 13, 1, 19, 50)

In [41]:
x = pd.Timestamp(dt.datetime(2025,10,13,1,19,50))
x

Timestamp('2025-10-13 01:19:50')

In [53]:
## fetching attributes
x.year
x.month
x.day
x.hour
x.minute
x.second

50

In [55]:
## why seprate objects to handle date and time when python already has datetime functionality

* Syntax wise datetime is very convenient
* but the performance takes a hit while working with huge data . List vs Numpy Array
* The weekness of Python's datetime format inspired the Numpy team to add a set of native time series data type to Numpy.
* The datetime64  dtype encodes dates as 64-bit integers , and thus allows arrays of dates to be represented very compactly

In [58]:
import numpy as np
date = np.array('2025-08-04',dtype=np.datetime64)
date

array('2025-08-04', dtype='datetime64[D]')

In [60]:
date + np.arange(12)

array(['2025-08-04', '2025-08-05', '2025-08-06', '2025-08-07',
       '2025-08-08', '2025-08-09', '2025-08-10', '2025-08-11',
       '2025-08-12', '2025-08-13', '2025-08-14', '2025-08-15'],
      dtype='datetime64[D]')

* Because of the uniform type in NumPy datetime64 arrays, this type of operation can be accomplished much more quickly than if we were working directly with Python's datetime objects, especially as arrays get large
* Pandas Timestamp object combines the ease-of-use of python datetime with the efficient storage and vectorized interface of numpy.datetime64
* From a group of these Timestamp objects, Pandas can construct a Datetimelndex that can be used to index data in a Series or DataFrame

## DateTimeIndex Objects
> A collection of pandas timestamp

In [68]:
## from strings
dt = pd.DatetimeIndex(['2020/3/4','2022/5/7','2025/3/12'])
dt

DatetimeIndex(['2020-03-04', '2022-05-07', '2025-03-12'], dtype='datetime64[ns]', freq=None)

In [70]:
type(dt)

pandas.core.indexes.datetimes.DatetimeIndex

In [72]:
dt[0]

Timestamp('2020-03-04 00:00:00')

In [74]:
type(dt[0])

pandas._libs.tslibs.timestamps.Timestamp

In [78]:
## using python datetime object
import datetime as dt
pd.DatetimeIndex([dt.datetime(2023,3,5),dt.datetime(2024,7,9),dt.datetime(2025,12,10)])

DatetimeIndex(['2023-03-05', '2024-07-09', '2025-12-10'], dtype='datetime64[ns]', freq=None)

In [84]:
## using pd.Timestamp
dt_index = pd.DatetimeIndex([pd.Timestamp(2023,3,5),pd.Timestamp(2024,7,9),pd.Timestamp(2025,12,10)])

In [86]:
## using datetime as series index
pd.Series([1,2,3],index=dt_index)

2023-03-05    1
2024-07-09    2
2025-12-10    3
dtype: int64

### date_range function

In [89]:
## generate daily dates in a given range
pd.date_range(start='2025/10/01',end='2025/10/30',freq='D')

DatetimeIndex(['2025-10-01', '2025-10-02', '2025-10-03', '2025-10-04',
               '2025-10-05', '2025-10-06', '2025-10-07', '2025-10-08',
               '2025-10-09', '2025-10-10', '2025-10-11', '2025-10-12',
               '2025-10-13', '2025-10-14', '2025-10-15', '2025-10-16',
               '2025-10-17', '2025-10-18', '2025-10-19', '2025-10-20',
               '2025-10-21', '2025-10-22', '2025-10-23', '2025-10-24',
               '2025-10-25', '2025-10-26', '2025-10-27', '2025-10-28',
               '2025-10-29', '2025-10-30'],
              dtype='datetime64[ns]', freq='D')

In [91]:
pd.date_range(start='2025/10/01',end='2025/10/30',freq='2D')

DatetimeIndex(['2025-10-01', '2025-10-03', '2025-10-05', '2025-10-07',
               '2025-10-09', '2025-10-11', '2025-10-13', '2025-10-15',
               '2025-10-17', '2025-10-19', '2025-10-21', '2025-10-23',
               '2025-10-25', '2025-10-27', '2025-10-29'],
              dtype='datetime64[ns]', freq='2D')

In [93]:
pd.date_range(start='2025/10/01',end='2025/10/30',freq='3D')

DatetimeIndex(['2025-10-01', '2025-10-04', '2025-10-07', '2025-10-10',
               '2025-10-13', '2025-10-16', '2025-10-19', '2025-10-22',
               '2025-10-25', '2025-10-28'],
              dtype='datetime64[ns]', freq='3D')

In [95]:
## B -> business days
pd.date_range(start='2025/10/01',end='2025/10/30',freq='B')

DatetimeIndex(['2025-10-01', '2025-10-02', '2025-10-03', '2025-10-06',
               '2025-10-07', '2025-10-08', '2025-10-09', '2025-10-10',
               '2025-10-13', '2025-10-14', '2025-10-15', '2025-10-16',
               '2025-10-17', '2025-10-20', '2025-10-21', '2025-10-22',
               '2025-10-23', '2025-10-24', '2025-10-27', '2025-10-28',
               '2025-10-29', '2025-10-30'],
              dtype='datetime64[ns]', freq='B')

In [97]:
## W -> one week per day
pd.date_range(start='2025/10/01',end='2025/10/30',freq='W')

DatetimeIndex(['2025-10-05', '2025-10-12', '2025-10-19', '2025-10-26'], dtype='datetime64[ns]', freq='W-SUN')

In [99]:
pd.date_range(start='2025/10/01',end='2025/10/30',freq='W-Thu')

DatetimeIndex(['2025-10-02', '2025-10-09', '2025-10-16', '2025-10-23',
               '2025-10-30'],
              dtype='datetime64[ns]', freq='W-THU')

In [103]:
## H -> Hourly date(factor)
pd.date_range(start='2025/10/01',end='2025/10/30',freq='h')

DatetimeIndex(['2025-10-01 00:00:00', '2025-10-01 01:00:00',
               '2025-10-01 02:00:00', '2025-10-01 03:00:00',
               '2025-10-01 04:00:00', '2025-10-01 05:00:00',
               '2025-10-01 06:00:00', '2025-10-01 07:00:00',
               '2025-10-01 08:00:00', '2025-10-01 09:00:00',
               ...
               '2025-10-29 15:00:00', '2025-10-29 16:00:00',
               '2025-10-29 17:00:00', '2025-10-29 18:00:00',
               '2025-10-29 19:00:00', '2025-10-29 20:00:00',
               '2025-10-29 21:00:00', '2025-10-29 22:00:00',
               '2025-10-29 23:00:00', '2025-10-30 00:00:00'],
              dtype='datetime64[ns]', length=697, freq='h')

In [105]:
pd.date_range(start='2025/10/01',end='2025/10/30',freq='6h')

DatetimeIndex(['2025-10-01 00:00:00', '2025-10-01 06:00:00',
               '2025-10-01 12:00:00', '2025-10-01 18:00:00',
               '2025-10-02 00:00:00', '2025-10-02 06:00:00',
               '2025-10-02 12:00:00', '2025-10-02 18:00:00',
               '2025-10-03 00:00:00', '2025-10-03 06:00:00',
               ...
               '2025-10-27 18:00:00', '2025-10-28 00:00:00',
               '2025-10-28 06:00:00', '2025-10-28 12:00:00',
               '2025-10-28 18:00:00', '2025-10-29 00:00:00',
               '2025-10-29 06:00:00', '2025-10-29 12:00:00',
               '2025-10-29 18:00:00', '2025-10-30 00:00:00'],
              dtype='datetime64[ns]', length=117, freq='6h')

In [115]:
## ME -> month end
pd.date_range(start='2025/10/01',end='2025/12/05',freq='ME')

DatetimeIndex(['2025-10-31', '2025-11-30'], dtype='datetime64[ns]', freq='ME')

In [117]:
## MS ->month start
pd.date_range(start='2025/10/01',end='2025/12/05',freq='MS')

DatetimeIndex(['2025-10-01', '2025-11-01', '2025-12-01'], dtype='datetime64[ns]', freq='MS')

In [121]:
## YE -> year end
pd.date_range(start='2025/10/01',end='2029/12/05',freq='YE')

DatetimeIndex(['2025-12-31', '2026-12-31', '2027-12-31', '2028-12-31'], dtype='datetime64[ns]', freq='YE-DEC')

In [123]:
## YS -> year start
pd.date_range(start='2025/10/01',end='2029/12/05',freq='YS')

DatetimeIndex(['2026-01-01', '2027-01-01', '2028-01-01', '2029-01-01'], dtype='datetime64[ns]', freq='YS-JAN')

In [129]:
## using periods (number of results)
pd.date_range(start='2025/10/13',periods=25,freq='5h')

DatetimeIndex(['2025-10-13 00:00:00', '2025-10-13 05:00:00',
               '2025-10-13 10:00:00', '2025-10-13 15:00:00',
               '2025-10-13 20:00:00', '2025-10-14 01:00:00',
               '2025-10-14 06:00:00', '2025-10-14 11:00:00',
               '2025-10-14 16:00:00', '2025-10-14 21:00:00',
               '2025-10-15 02:00:00', '2025-10-15 07:00:00',
               '2025-10-15 12:00:00', '2025-10-15 17:00:00',
               '2025-10-15 22:00:00', '2025-10-16 03:00:00',
               '2025-10-16 08:00:00', '2025-10-16 13:00:00',
               '2025-10-16 18:00:00', '2025-10-16 23:00:00',
               '2025-10-17 04:00:00', '2025-10-17 09:00:00',
               '2025-10-17 14:00:00', '2025-10-17 19:00:00',
               '2025-10-18 00:00:00'],
              dtype='datetime64[ns]', freq='5h')

### to_datetime function
>  converts an existing objects to pandas timestamp / datetimeindex object

In [148]:
## simple series example

s = pd.Series(['2025/10/13','2024/10/13','2023/10/13'])
pd.to_datetime(s).dt.year
pd.to_datetime(s).dt.month
pd.to_datetime(s).dt.day
pd.to_datetime(s).dt.month_name()
pd.to_datetime(s).dt.day_name()

0    Monday
1    Sunday
2    Friday
dtype: object

In [156]:
## with errors

s = pd.Series(['2025/10/13','2024/10/13','2023/100/13'])
print(s)
pd.to_datetime(s,errors='coerce')

0     2025/10/13
1     2024/10/13
2    2023/100/13
dtype: object

0   2025-10-13
1   2024-10-13
2          NaT
dtype: datetime64[ns]

In [160]:
## 
df = pd.read_csv('expense_data.csv')
df.head()

,Date,Account,Category,Subcategory,Note,INR,Income/Expense,Note.1,Amount,Currency,Account.1
0,3/2/2022 10:11,CUB - online payment,Food,NaN,Brownie,50.0,Expense,NaN,50.0,INR,50.0
1,3/2/2022 10:11,CUB - online payment,Other,NaN,To lended people,300.0,Expense,NaN,300.0,INR,300.0
2,3/1/2022 19:50,CUB - online payment,Food,NaN,Dinner,78.0,Expense,NaN,78.0,INR,78.0
3,3/1/2022 18:56,CUB - online payment,Transportation,NaN,Metro,30.0,Expense,NaN,30.0,INR,30.0
4,3/1/2022 18:22,CUB - online payment,Food,NaN,Snacks,67.0,Expense,NaN,67.0,INR,67.0

In [162]:
df['Date'] = pd.to_datetime(df['Date'])

In [164]:
df.head()

,Date,Account,Category,Subcategory,Note,INR,Income/Expense,Note.1,Amount,Currency,Account.1
0,2022-03-02 10:11:00,CUB - online payment,Food,NaN,Brownie,50.0,Expense,NaN,50.0,INR,50.0
1,2022-03-02 10:11:00,CUB - online payment,Other,NaN,To lended people,300.0,Expense,NaN,300.0,INR,300.0
2,2022-03-01 19:50:00,CUB - online payment,Food,NaN,Dinner,78.0,Expense,NaN,78.0,INR,78.0
3,2022-03-01 18:56:00,CUB - online payment,Transportation,NaN,Metro,30.0,Expense,NaN,30.0,INR,30.0
4,2022-03-01 18:22:00,CUB - online payment,Food,NaN,Snacks,67.0,Expense,NaN,67.0,INR,67.0

In [166]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 277 entries, 0 to 276
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Date            277 non-null    datetime64[ns]
 1   Account         277 non-null    object
 2   Category        277 non-null    object
 3   Subcategory     0 non-null      float64
 4   Note            273 non-null    object
 5   INR             277 non-null    float64
 6   Income/Expense  277 non-null    object
 7   Note.1          0 non-null      float64
 8   Amount          277 non-null    float64
 9   Currency        277 non-null    object
 10  Account.1       277 non-null    float64
dtypes: datetime64[ns](1), float64(5), object(5)
memory usage: 23.9+ KB

In [174]:
df['Date'].dt.is_month_end
df['Date'].dt.is_month_start
df['Date'].dt.is_quarter_start
df['Date'].dt.is_quarter_end

0      False
1      False
2      False
3      False
4      False
       ...
272    False
273    False
274    False
275    False
276    False
Name: Date, Length: 277, dtype: bool