In [28]:
import pandas as pd

In [30]:
var = pd.DataFrame({"A":[3,4,5,6,7],"B":[9,8,7,6,5]})
var

   A  B
0  3  9
1  4  8
2  5  7
3  6  6
4  7  5

In [32]:
var.insert(2,"Python2",var["A"])
var

   A  B  Python2
0  3  9        3
1  4  8        4
2  5  7        5
3  6  6        6
4  7  5        7

In [34]:
var.insert(2,"Python3",[3,4,5,6,8])
var

   A  B  Python3  Python2
0  3  9        3        3
1  4  8        4        4
2  5  7        5        5
3  6  6        6        6
4  7  5        8        7

In [40]:
var1 = pd.DataFrame({"A":[3,2,4,5,6],"B":[9,8,7,6,5]})
var1

   A  B
0  3  9
1  2  8
2  4  7
3  5  6
4  6  5

In [42]:
var1["Python_12"]=var1["A"][:3]
var1

   A  B  Python_12
0  3  9        3.0
1  2  8        2.0
2  4  7        4.0
3  5  6        NaN
4  6  5        NaN

DELETE

In [45]:
var = pd.DataFrame({"A":[1,2,3,4,5],"B":[4,5,6,7,8],"C":[12,13,14,34,56]})
var

   A  B   C
0  1  4  12
1  2  5  13
2  3  6  14
3  4  7  34
4  5  8  56

In [47]:
var1 = var.pop("B")
var1

0    4
1    5
2    6
3    7
4    8
Name: B, dtype: int64

In [49]:
var

   A   C
0  1  12
1  2  13
2  3  14
3  4  34
4  5  56

In [53]:
 del var["A"]
var

    C
0  12
1  13
2  14
3  34
4  56