Melt()

In [2]:
import pandas as pd

In [4]:
var = pd.DataFrame({"days":[1,2,3,4,5,6],"eng":[10,12,14,15,16,12],"maths":[17,18,19,20,13,14]})
var

   days  eng  maths
0     1   10     17
1     2   12     18
2     3   14     19
3     4   15     20
4     5   16     13
5     6   12     14

In [6]:
pd.melt(var)

   variable  value
0      days      1
1      days      2
2      days      3
3      days      4
4      days      5
5      days      6
6       eng     10
7       eng     12
8       eng     14
9       eng     15
10      eng     16
11      eng     12
12    maths     17
13    maths     18
14    maths     19
15    maths     20
16    maths     13
17    maths     14

In [8]:
pd.melt(var,id_vars=["days"])

    days variable  value
0      1      eng     10
1      2      eng     12
2      3      eng     14
3      4      eng     15
4      5      eng     16
5      6      eng     12
6      1    maths     17
7      2    maths     18
8      3    maths     19
9      4    maths     20
10     5    maths     13
11     6    maths     14

In [12]:
pd.melt(var,id_vars=["days"],var_name="Python")

    days Python  value
0      1    eng     10
1      2    eng     12
2      3    eng     14
3      4    eng     15
4      5    eng     16
5      6    eng     12
6      1  maths     17
7      2  maths     18
8      3  maths     19
9      4  maths     20
10     5  maths     13
11     6  maths     14

In [14]:
pd.melt(var,id_vars=["days"],var_name="Python",value_name="wscube")

    days Python  wscube
0      1    eng      10
1      2    eng      12
2      3    eng      14
3      4    eng      15
4      5    eng      16
5      6    eng      12
6      1  maths      17
7      2  maths      18
8      3  maths      19
9      4  maths      20
10     5  maths      13
11     6  maths      14

Pivot()

In [21]:
var = pd.DataFrame({"days":[1,2,3,4,5,6],"st_name":['a','b','b','a','b','b'],"eng":[10,12,14,15,16,12],"maths":[17,18,19,20,13,14]})
var

   days st_name  eng  maths
0     1       a   10     17
1     2       b   12     18
2     3       b   14     19
3     4       a   15     20
4     5       b   16     13
5     6       b   12     14

In [23]:
var.pivot(index="days",columns="st_name")

          eng       maths
st_name     a     b     a     b
days
1        10.0   NaN  17.0   NaN
2         NaN  12.0   NaN  18.0
3         NaN  14.0   NaN  19.0
4        15.0   NaN  20.0   NaN
5         NaN  16.0   NaN  13.0
6         NaN  12.0   NaN  14.0

In [25]:
var.pivot(index="days",columns="st_name",values="eng")

st_name     a     b
days
1        10.0   NaN
2         NaN  12.0
3         NaN  14.0
4        15.0   NaN
5         NaN  16.0
6         NaN  12.0

In [35]:
var = pd.DataFrame({"days":[1,1,1,1,2,2],"st_name":['a','b','b','a','b','b'],"eng":[10,12,14,15,16,12],"maths":[17,18,19,20,13,14]})
var

   days st_name  eng  maths
0     1       a   10     17
1     1       b   12     18
2     1       b   14     19
3     1       a   15     20
4     2       b   16     13
5     2       b   12     14

In [39]:
var.pivot_table(index="st_name",columns='days',aggfunc="mean",margins = True)

           eng                  maths
days         1     2        All     1     2        All
st_name
a        12.50   NaN  12.500000  18.5   NaN  18.500000
b        13.00  14.0  13.500000  18.5  13.5  16.000000
All      12.75  14.0  13.166667  18.5  13.5  16.833333